### ISSUE TITLE
difficulty getting remove to work

### ISSUE THREAD

**Issue by cognizen** [racker/node-elementtree#23]
I'm not sure if this is a bug or me not quite grokking the system.  I have been utilizing node-eleementtree for some time to populate xml documents and have had no problem but I have recently tried to utilize the remove function and am getting errors.

I'm doing a pretty basic settup: 

```javascript
fs.readFile(coursePath, function(err, data){
    var XML = et.XML;
    var ElementTree = et.ElementTree;
    var element = et.Element;
    var subElement = et.SubElement;

    var _data, etree;

    _data = data.toString();
    etree = et.parse(_data);
    var stringID = content.id.toString();
    console.log(etree.find('./item/[@id="'+stringID+'"]'));
    var myitem = etree.find('./item/[@id="'+stringID+'"]');
```

I'm identifying the element that I want to remove in the myitem variable.  But when I run:
```javascript
etree.remove(myitem);
```
I'm getting the following error:

[TypeError: undefined is not a function]
TypeError: undefined is not a function
   at /Users/xxxxxxx/Sites/xxxxxx/bin/server/xxxxxxx-socket-handler.js:915:19
   at fs.js:291:14
   at Object.oncomplete (fs.js:97:15)

Is this an issue with the system or with the user?

Best,
Phil

**Comment by shazron** [comment]
Try:
```etree.getroot().remove(myitem)```

**Comment by cognizen** [comment]
Excellent - thank you!
